---
abstract: 'Dumps pre defined scripts!'
author:
  - 'Ariel Vieira <ariel.vieira@yandex.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-FileComposer
provides:
  App::FileComposer:
    file: lib/App/FileComposer.pm
    version: '0.01'
requires:
  Carp: '1.52'
  Moose: '2.2203'
  Term::ANSIColor: '5.01'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
